{{- if .Values.headlessService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-grpc.fullname" . }}-headless
  namespace: {{ include "go-grpc.namespace" . }}
  labels:
    {{- include "go-grpc.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "go-grpc.selectorLabels" . | nindent 4 }}
{{- end }}
